# Generated by Django 5.0.4 on 2024-05-09 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('height', models.CharField(max_length=10)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('dietary_preference', models.CharField(choices=[('vegitarian', 'Vegitarian'), ('vegan', 'Vegan'), ('no_preference', 'No Preference')], max_length=50)),
            ],
        ),
    ]
